config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in' , as: 'users_guest_sign_in'
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  get '/auth/:provider/callback', to: 'users/omniauth_callbacks#yahoojp', as:'get_callback'
  post '/auth/:provider/callback', to: 'users/omniauth_callbacks#yahoojp', as:'post_callback'
  
  get '/auth/failure', to: 'sessions#failure', as:'failure_session'

  get '/', to:'reservations#index', as:'index_reservation'

  get 'reservations/show/:date', to:'reservations#show', as:'show_reservation'

  get 'reservations/new/:date/:time_slot', to:'reservations#new', as:'new_reservation'
  post 'reservations/new/:date/:time_slot', to:'reservations#create', as:'create_reservation'

  get 'reservations/confirm', to:'reservations#confirm', as:'confirm_reservation'  
  delete 'reservations/confirm/destroy/:id', to:'reservations#destroy', as:'destroy_reservation'
  
  get 'users/show', to:'users#show', as:'show_user'
  patch 'users/show', to:'users#update', as:'update_user'

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, omniauth_providers: %i[line]
  
  has_many :reservations, dependent: :destroy

  validates :name, presence: true, unless: :guest?
  validates :email, presence: true, unless: :guest?
  validates :phone_number, presence: true, unless: :guest?
  
  def self.guest
    find_or_create_by!(email: 'guest@example.com') do |user|
      user.password = SecureRandom.urlsafe_base64
      user.name = ''
      user.phone_number = ''
    end
  end
  
  def guest?
    email == 'guest@example.com'
  end

end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
    def facebook
        # Facebook 認証のコールバック処理
    end

    def line

    end

    def google_oauth2

    end

    def yahoojp
        auth = request.env['omniauth.auth']

        @user_id = auth.uid

        @name  = auth.info.name
        @email = auth.info.email
        @first_name = auth.info.first_name
        @last_name  = auth.info.last_name

        @token         = auth.credentials.token;
        @refresh_token = auth.credentials.refresh_token;
        @expires_at    = auth.credentials.expires_at;

        render 'users/callback'
    end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
    def guest_sign_in
        user = User.guest
        sign_in user
        redirect_to index_reservation_path, notice: 'ゲストユーザーとしてログインしました。'
    end
    
    
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :authenticate_user!
    before_action :check_guest, only: [:show]

    def show
        @user = current_user
    end

    def update
        @user = current_user
        if @user.update(user_params)
            redirect_to index_reservation_path(@user), notice: 'ユーザー情報を更新しました'
        else
            render :show
        end
    end

    private
    def check_guest
        if current_user.email == 'guest@example.com' 
            redirect_to index_reservation_path, alert: "ゲストユーザーはこのページにアクセスできません。"
        end
    end

    def user_params
        params.require(:user).permit(:name, :email, :phone_number)
    end


end

app/views/users/callback.html.erb
<div id="user">
    <p>Hello, <%= @name %> さん</p>
    <div id="credentials">
        Credentials:
        <ul>
            <li>access_token: <%= @token %></li>
            <li>refresh_token: <%= @refresh_token %></li>
            <li>expires_at: <%= @expires_at %></li>
        </ul>
    </div>
    <div id="userinfo">
        UserInfo:
        <ul>
            <li>user_id:    <%= @user_id %></li>
            <li>email:      <%= @email %></li>
            <li>name:       <%= @name %></li>
            <li>first_name: <%= @first_name %></li>
            <li>last_name:  <%= @last_name %></li>
        </ul>
    </div>
</div>

app/views/users/show.html.erb
<%= form_for @user, url: update_user_path, method: :patch do |f| %>
    <div class="form-group">
        <%= f.label :name, "名前" %>
        <%= f.text_field :name, class: 'form-control' %>
    </div>

    <div class="form-group">
        <%= f.label :email, "メールアドレス" %>
        <%= f.email_field :email, class: 'form-control' %>
    </div>

    <div class="form-group">
        <%= f.label :phone_number, "電話番号" %>
        <%= f.text_field :phone_number, class: 'form-control' %>
    </div>

    <%= f.submit "更新", class: 'btn btn-primary' %>
<% end %>