config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in' , as: 'users_guest_sign_in'
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  get '/auth/:provider/callback', to: 'users/omniauth_callbacks#yahoojp', as:'get_callback'
  post '/auth/:provider/callback', to: 'users/omniauth_callbacks#yahoojp', as:'post_callback'
  
  get '/auth/failure', to: 'sessions#failure', as:'failure_session'

  get '/', to:'reservations#index', as:'index_reservation'

  get 'reservations/show/:date', to:'reservations#show', as:'show_reservation'

  get 'reservations/new/:date/:time_slot', to:'reservations#new', as:'new_reservation'
  post 'reservations/new/:date/:time_slot', to:'reservations#create', as:'create_reservation'

  get 'reservations/confirm', to:'reservations#confirm', as:'confirm_reservation'  
  delete 'reservations/confirm/destroy/:id', to:'reservations#destroy', as:'destroy_reservation'
  
  get 'users/show', to:'users#show', as:'show_user'
  patch 'users/show', to:'users#update', as:'update_user'

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/reservation.rb
class Reservation < ApplicationRecord
    belongs_to :user
    validates :note, length: { maximum: 300 }, allow_blank: true
    
    def self.total_reservations_for_time_slot(time_slot)
        where(time_slot: time_slot).sum(:adults) + where(time_slot: time_slot).sum(:children)
    end
    
    def self.total_reservations_for_time_range(start_time, end_time)
        where(time_slot: start_time..end_time).sum(:adults) + where(time_slot: start_time..end_time).sum(:children)
    end
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
    before_action :authenticate_user!
    before_action :validate_max_people_per_time_slot, only: [:create]
    before_action :total_people_count_within_limit, only: [:create]
    before_action :ensure_authenticated_user!, only: [:confirm]

    def index
        #1ヶ月のカレンダー表示
        require "date"
        @start_date = Date.today
        @end_date = @start_date + 1.month
        @dates = (@start_date..@end_date).to_a
        @reservations = current_user.reservations
    end

    def show
        #日にち詳細画面に遷移して予約状況を示す
        @date = Date.parse(params[:date])
        @time_slots = (18..20).flat_map { |hour| ["#{hour}:00", "#{hour}:30"] }
        @reservations = Reservation.where(date: @date).group(:time_slot).sum(:adults)
    end

    def new
        #予約を確定させていく画面
        @reservation = Reservation.new
        @reservation.date = params[:date]
        @reservation.time_slot = params[:time_slot]
        if user_signed_in?
            @reservation.user = current_user
        end
        end_time = (Time.parse(params[:time_slot]) + 2.hours).strftime("%H:%M")
        total_reserved = Reservation.total_reservations_for_time_range(params[:time_slot], end_time)
        @remaining_seats = 20 - total_reserved
    end

    def create
        @reservation = Reservation.new(date: params[:date], time_slot: params[:time_slot], adults: params[:reservation][:adults], children: params[:reservation][:children], note: params[:reservation][:note])
        temp_name = params[:reservation][:name]
        temp_email = params[:reservation][:email]
        temp_phone_number = params[:reservation][:phone_number]
        @reservation.user = current_user
        
        if current_user.guest? && (temp_name.blank? || temp_email.blank? || temp_phone_number.blank?)
            flash[:alert] = "名前、メールアドレス、電話番号を正しく入力してください。"
            render :new
            return
        end

        unless total_people_count_within_limit
            flash[:alert] = @reservation_error
            render :new
            return
        end

        if @reservation.save
            current_user.update(name: temp_name, email: temp_email, phone_number: temp_phone_number) unless current_user.guest?
            flash[:notice] = '予約が完了しました。'
            redirect_to index_reservation_path 
        else
            flash[:alert] = '予約に失敗しました。もう一度やり直してください。'
            render :new
        end
        
    end

    def confirm
        @reservations = current_user.reservations.where('date >= ?', Date.today)        
        unless @reservations.exists?
            flash[:alert] = "予約が見つかりませんでした。"
            redirect_to index_reservation_path and return
        end
        render :confirm
    end

    def destroy
        @reservations = Reservation.find_by_id(params[:id])
        if @reservations
            @reservations.destroy
            redirect_to confirm_reservation_path, notice: '予約をキャンセルしました。'
        end
    end

    private
    def reservation_params
        params.require(:reservation).permit(:date, :time_slot, :adults, :children, :note, :name, :email, :phone_number)
    end

    def validate_max_people_per_time_slot
        existing_reservations = Reservation.where(date: params[:date], time_slot: params[:time_slot])
        total_people_existing = existing_reservations.sum(:adults) + existing_reservations.sum(:children)
        total_people_new = params[:reservation][:adults].to_i + params[:reservation][:children].to_i
        
        if total_people_existing + total_people_new > 20
            flash[:alert] = 'この時間帯の予約は20人までです。'
            redirect_to new_reservation_path
        end
    end

    def total_people_count_within_limit
        total_adults_already_reserved = Reservation.where(date: params[:reservation][:date], time_slot: params[:reservation][:time_slot]).sum(:adults)
        total_children_already_reserved = Reservation.where(date: params[:reservation][:date], time_slot: params[:reservation][:time_slot]).sum(:children)   
        total_people_already_reserved = total_adults_already_reserved + total_children_already_reserved
        total_people_for_new_reservation = params[:reservation][:adults].to_i + params[:reservation][:children].to_i
        
        if total_people_already_reserved + total_people_for_new_reservation > 20
            @reservation_error = "総数が20人を超えています。人数を減らしてください。"
            false
        else
            true
        end
    end
    
    def ensure_authenticated_user!
        if current_user&.guest?
            redirect_to index_reservation_path, alert: 'ゲストユーザーはこのページにアクセスできません。'
        end
    end

end

app/helpers/reservation_helper.rb
module ReservationHelper
    def reservation_status_symbol(reservations_count)
        case reservations_count
        when 0
            '⚪︎'
        when 1..10 
            '△'
        else
            '×'
        end
    end
end

app/views/reservations/confirm.html.erb
<h2>予約内容</h2>

<% @reservations.each do |reservation| %>
        <div class="reservation-entry">
                <p>日付: <%= reservation.date.strftime("%Y年%m月%d日") %> <%= reservation.time_slot %></p>
                <p>大人の人数: <%= reservation.adults %></p>
                <p>子供の人数：<%= reservation.children %></p>
                <p>備考： <%= reservation.note%></p>

                <p>予約ID: <%= reservation.id %></p>

                <%= button_to "キャンセルする", destroy_reservation_path(reservation), method: :delete, data: { confirm: '本当にキャンセルしますか？' }, class: "delete-btn" %>
        </div>
<% end %>




<%= link_to "戻る", index_reservation_path %>

app/views/reservations/index.html.erb
<h1>予約カレンダー</h1>

<table class="calendar">
    <thead>
        <tr>
            <th>日</th>
            <th>月</th>
            <th>火</th>
            <th>水</th>
            <th>木</th>
            <th>金</th>
            <th>土</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <% @dates.each do |date| %>
                <% if date == @dates.first %>
                    <% date.wday.times do %>
                        <td></td>
                    <% end %>
                <% end %>

                <td><%= link_to date.day, show_reservation_path(date) %></td>
                
                <% if date.wday == 6 %>
                    </tr>
                    <tr>
                <% end %>
            <% end %>
        </tr>
        
        <tr>
            <td colspan="7">
                <%= link_to "予約の確認", confirm_reservation_path %>
            </td>
        </tr>
        
    </tbody>
</table>
<% if user_signed_in? %>
    <%= link_to "ログアウト", destroy_user_session_path, method: :delete %>
<% end %>

app/views/reservations/new.html.erb
<h1>新規予約</h1>
<%= @remaining_seats %>人まで予約可能です。
<%= form_with model: @reservation, url: create_reservation_path ,local: true do |f| %>
    <div class="form-group">
        <label for="reservation_name">名前:</label>
        <%= f.text_field :name, value: user_signed_in? ? current_user.name : '', class: 'form-control', placeholder: '名前を入力してください', required: true %>
    </div>

    <div class="form-group">
        <label for="reservation_email">メールアドレス:</label>
        <%= f.email_field :email, value: user_signed_in? ? current_user.email : '', class: 'form-control', placeholder: 'メールアドレスを入力してください', required: true %>
    </div>

    <div class="form-group">
        <label for="reservation_phone_number">電話番号:</label>
        <%= f.telephone_field :phone_number, value: user_signed_in? ? current_user.phone_number : '', class: 'form-control', placeholder: '電話番号を入力してください', required: true %>
    </div>

    <div class="form-group">
        <label for="reservation_date">希望日時:</label>
        <p>
        
        <%= @reservation.time_slot %> 
        </p>
        <%= f.hidden_field :date %>
        <%= f.hidden_field :time_slot %>
    </div>

    <div class="form-group">
        <label for="reservation_adults">大人の人数:</label>
        <%= f.select :adults, options_for_select((1..10).to_a), {}, class: 'form-control' %>
    </div>

    <div class="form-group">
        <label for="reservation_children">子供の人数:</label>
        <%= f.select :children, options_for_select((0..10).to_a), {}, class: 'form-control' %>
    </div>

    <div class="form-group">
        <label for="reservation_note">備考:</label>
        <%= f.text_area :note, class: 'form-control', placeholder: '要望などがあれば入力してください', rows: 5 %>
    </div>

    <div class="actions">
        <%= f.submit '予約する', class: 'btn btn-primary' %>
    </div>
<% end %>

app/views/reservations/show.html.erb
<h2>Reservations for <%= @date.strftime("%Y-%m-%d") %></h2>

<table>
    <thead>
        <tr>
            <th>Time Slot</th>
            <th>Reservation Status</th>
        </tr>
    </thead>
    <tbody>
        <% @time_slots.each do |slot| %>
            <tr>
                <td><%= slot %></td>
                <td>
                    <% count = @reservations[slot] || 0 %>
                    <% status = reservation_status_symbol(count) %>
                    <%= status%>
                    <% if status == "⚪︎" || status == "△" %>
                        <%= button_to "予約へ", new_reservation_path(date: @date, time_slot: slot), method: :get %>
                    <% end %>
                    
                </td>
            </tr>
        <% end %>
    </tbody>
</table>