config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in' , as: 'users_guest_sign_in'
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  get '/auth/:provider/callback', to: 'users/omniauth_callbacks#yahoojp', as:'get_callback'
  post '/auth/:provider/callback', to: 'users/omniauth_callbacks#yahoojp', as:'post_callback'
  
  get '/auth/failure', to: 'sessions#failure', as:'failure_session'

  get '/', to:'reservations#index', as:'index_reservation'

  get 'reservations/show/:date', to:'reservations#show', as:'show_reservation'

  get 'reservations/new/:date/:time_slot', to:'reservations#new', as:'new_reservation'
  post 'reservations/new/:date/:time_slot', to:'reservations#create', as:'create_reservation'

  get 'reservations/confirm', to:'reservations#confirm', as:'confirm_reservation'  
  delete 'reservations/confirm/destroy/:id', to:'reservations#destroy', as:'destroy_reservation'
  
  get 'users/show', to:'users#show', as:'show_user'
  patch 'users/show', to:'users#update', as:'update_user'

  # Defines the root path route ("/")
  # root "articles#index"
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ja">
  <head>
    
    <title>SNS App</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <link rel="stylesheet" href="<%= mix('/css/app.css') %>">
    
    <script src="<%= mix('/js/bootstrap.js') %>"></script>
  </head>

  <body>
    <div class="main-container">
      
      <nav class="custom-navbar">
        <div id="menuToggle">
          <input type="checkbox" />
          <span></span>
          <span></span>
          <span></span>
          <ul id="menu">
            <li>
              <a href="#">投稿一覧</a>
            </li>
            <li>
              <a href="#">新規投稿</a>
            </li>
            <li>
              <a href="<%= show_user_path %>">本人情報</a>
            </li>
          </ul>
        </div>
      </nav>

      
      <% if notice %>
        <div class="alert alert-success" role="alert">
          <%= notice %>
        </div>
      <% end %>
      <% if alert %>
        <div class="alert alert-danger" role="alert">
          <%= alert %>
        </div>
      <% end %>

      <div class="bg-white text-dark">
        <%= yield %>
      </div>
    </div>

  
    <script src="<%= mix('/js/app.js') %>"></script>
    <script src="<%= mix('/js/confirm-reservation.js') %>"></script>
  </body>
</html>